### ISSUE TITLE
add-view: InvalidTransactionState: cannot start subtransactions during a parallel operation

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-summarize#175]
**Which service is affected?**

Kingfisher Summarize
process.kingfisher.open-contracting.org

**What were you trying to do?**

Add a view.

I tried running `manage.py` per the [updated docs](https://kingfisher-summarize.readthedocs.io/en/latest/cli/use.html#summarize-many-collections) but the updates don't seem to have been deployed, so I tried using the old cli interface which didn't work either.

```
ssh ocdskfp@process.kingfisher.open-contracting.org
cd ocdskingfisherviews
python ocdskingfisher-views-cli add-view 1593,1594,1595 "Created by Duncan to check updated Moldova data."
```

**What error did you receive?**

```
2020-11-12 00:34:54,458 - 864 - ocdskingfisher.views.cli - INFO - Running add-view
2020-11-12 00:34:54,472 - 864 - ocdskingfisher.views.add-view - INFO - Arguments: collections=(1593, 1594, 1595) note=Created by Duncan to check updated Moldova data. name=None tables_only=False
2020-11-12 00:34:54,498 - 864 - ocdskingfisher.views.add-view - INFO - Added collection_1593_1594_1595
2020-11-12 00:34:54,498 - 864 - ocdskingfisher.views.add-view - INFO - Running refresh-views routine
2020-11-12 00:34:54,521 - 864 - ocdskingfisher.views.refresh-views - INFO - Processing initial:flatten
2020-11-12 00:34:54,521 - 864 - ocdskingfisher.views.refresh-views - INFO - Processing initial:flatten
2020-11-12 00:34:54,538 - 864 - ocdskingfisher.views.refresh-views - INFO - initial:flatten: 0.017544031143188477s
2020-11-12 00:34:54,539 - 864 - ocdskingfisher.views.refresh-views - INFO - Processing initial:functions
2020-11-12 00:34:54,539 - 864 - ocdskingfisher.views.refresh-views - INFO - Processing initial:functions
2020-11-12 00:34:54,570 - 864 - ocdskingfisher.views.refresh-views - INFO - initial:functions: 0.030684709548950195s
2020-11-12 00:34:54,600 - 870 - ocdskingfisher.views.refresh-views - INFO - Processing middle:release_tmp
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/ocdskfp/ocdskingfisherviews/ocdskingfisherviews/cli.py", line 308, in _run_file
    db.execute(f'/* kingfisher-views {identifier} */\n' + content)
  File "/home/ocdskfp/ocdskingfisherviews/ocdskingfisherviews/db.py", line 59, in execute
    self.cursor.execute(statement, variables)
psycopg2.errors.InvalidTransactionState: cannot start subtransactions during a parallel operation
CONTEXT:  PL/pgSQL function convert_to_timestamp(text) line 2 during statement block entry

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ocdskingfisher-views-cli", line 5, in <module>
    cli()
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ocdskfp/ocdskingfisherviews/ocdskingfisherviews/cli.py", line 250, in add_view
    refresh_views(schema, tables_only=tables_only)
  File "/home/ocdskfp/ocdskingfisherviews/ocdskingfisherviews/cli.py", line 362, in refresh_views
    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
psycopg2.errors.InvalidTransactionState: cannot start subtransactions during a parallel operation
CONTEXT:  PL/pgSQL function convert_to_timestamp(text) line 2 during statement block entry
```

**Did you attempt a fix?**

No

**How soon do you need a fix?**

ASAP, needed for publisher feedback.

**Comment by jpmckinney** [comment]
I was waiting for the Moldova crawl to finish before deploying. Now deployed.

Bug fixed by e911e89. Currently adding schema.

**Comment by jpmckinney** [comment]
view_data_collection_1593_1594_1595 now exists.

**Comment by jpmckinney** [comment]
I'm not sure what test to write for the bug, since it seemed to only occur if the `convert_` functions were running in parallel *and* raised an exception.
