### ISSUE TITLE
Error when running the "add" function

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-summarize#226]
````
2023-07-20 19:35:18,373 - 51123 - ocdskingfisher.summarize.summary-tables - INFO - Processing middle:release_summary
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/summarize/kingfisher-summarize/manage.py", line 452, in _run_summary_tables
    db.execute(f'/* kingfisher-summarize {identifier} */\n' + content)
  File "/home/summarize/kingfisher-summarize/ocdskingfishersummarize/db.py", line 84, in execute
    self.cursor.execute(statement, variables)
psycopg2.errors.UndefinedColumn: column release_check.override_schema_version does not exist
LINE 69:         AND release_check.override_schema_version = ''
                     ^
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/summarize/kingfisher-summarize/manage.py", line 847, in <module>
    cli()
  File "/home/summarize/kingfisher-summarize/.ve/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/summarize/kingfisher-summarize/.ve/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/summarize/kingfisher-summarize/.ve/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/summarize/kingfisher-summarize/.ve/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/summarize/kingfisher-summarize/.ve/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/summarize/kingfisher-summarize/.ve/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/summarize/kingfisher-summarize/manage.py", line 373, in add
    summary_tables(schema, tables_only=tables_only, skip=skip, where_fragment=where_fragment)
  File "/home/summarize/kingfisher-summarize/manage.py", line 493, in summary_tables
    run_concurrently(graph, _run_summary_tables, lambda identifier: (name, identifier, files['middle'][identifier]))
  File "/home/summarize/kingfisher-summarize/manage.py", line 205, in run_concurrently
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
psycopg2.errors.UndefinedColumn: column release_check.override_schema_version does not exist
LINE 69:         AND release_check.override_schema_version = ''
````

**Comment by jpmckinney** [comment]
Closed by c393552 and deployed.
